name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies ⚡
        id: cache_dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          cd projects/todo-app && npm install
          cd ../notifications-page && npm install

      - name: Build projects
        run: |
          cd projects/todo-app && npm run build
          cd ../notifications-page && npm run build
      
      - name: Create .nojekyll file
        run: touch dist/notifications-page/.nojekyll

      - name: Copy static HTML project
        run: |
          mkdir -p dist/responsive-landing-page
          cp -r projects/responsive-landing-page/* dist/responsive-landing-page/

      - name: Copy index.html from repo
        run: cp projects/index.html dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
